#!/usr/bin/python
# -*- coding: utf-8 -*-

__version__ = '0.9.0'
__author = 'Christoph Schueler'
__copyright__ = """
 * k_dk - Driver Kit for k_os (Konnex Operating-System based on the
 * OSEK/VDX-Standard).
 *
 * (C) 2007-2012 by Christoph Schueler <github.com/Christoph2,
 *                                      cpu12.gems@googlemail.com>
 *
 * All Rights Reserved
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * s. FLOSS-EXCEPTION.txt
"""

import win32api

def CTL_CODE(DeviceType, Function, Method, Access ):
    return ((DeviceType) << 16) | ((Access) << 14) | ((Function) << 2) | (Method)


DELETE                          = 0x00010000
READ_CONTROL                    = 0x00020000
WRITE_DAC                       = 0x00040000
WRITE_OWNER                     = 0x00080000
SYNCHRONIZE                     = 0x00100000
STANDARD_RIGHTS_REQUIRED        = 0x000F0000
STANDARD_RIGHTS_READ            = READ_CONTROL
STANDARD_RIGHTS_WRITE           = READ_CONTROL
STANDARD_RIGHTS_EXECUTE         = READ_CONTROL
STANDARD_RIGHTS_ALL             = 0x001F0000
SPECIFIC_RIGHTS_ALL             = 0x0000FFFF

FILE_DEVICE_BEEP                = 0x00000001
FILE_DEVICE_CD_ROM              = 0x00000002
FILE_DEVICE_CD_ROM_FILE_SYSTEM  = 0x00000003
FILE_DEVICE_CONTROLLER          = 0x00000004
FILE_DEVICE_DATALINK            = 0x00000005
FILE_DEVICE_DFS                 = 0x00000006
FILE_DEVICE_DISK                = 0x00000007
FILE_DEVICE_DISK_FILE_SYSTEM    = 0x00000008
FILE_DEVICE_FILE_SYSTEM         = 0x00000009
FILE_DEVICE_INPORT_PORT         = 0x0000000a
FILE_DEVICE_KEYBOARD            = 0x0000000b
FILE_DEVICE_MAILSLOT            = 0x0000000c
FILE_DEVICE_MIDI_IN             = 0x0000000d
FILE_DEVICE_MIDI_OUT            = 0x0000000e
FILE_DEVICE_MOUSE               = 0x0000000f
FILE_DEVICE_MULTI_UNC_PROVIDER  = 0x00000010
FILE_DEVICE_NAMED_PIPE          = 0x00000011
FILE_DEVICE_NETWORK             = 0x00000012
FILE_DEVICE_NETWORK_BROWSER     = 0x00000013
FILE_DEVICE_NETWORK_FILE_SYSTEM = 0x00000014
FILE_DEVICE_NULL                = 0x00000015
FILE_DEVICE_PARALLEL_PORT       = 0x00000016
FILE_DEVICE_PHYSICAL_NETCARD    = 0x00000017
FILE_DEVICE_PRINTER             = 0x00000018
FILE_DEVICE_SCANNER             = 0x00000019
FILE_DEVICE_SERIAL_MOUSE_PORT   = 0x0000001a
FILE_DEVICE_SERIAL_PORT         = 0x0000001b
FILE_DEVICE_SCREEN              = 0x0000001c
FILE_DEVICE_SOUND               = 0x0000001d
FILE_DEVICE_STREAMS             = 0x0000001e
FILE_DEVICE_TAPE                = 0x0000001f
FILE_DEVICE_TAPE_FILE_SYSTEM    = 0x00000020
FILE_DEVICE_TRANSPORT           = 0x00000021
FILE_DEVICE_UNKNOWN             = 0x00000022
FILE_DEVICE_VIDEO               = 0x00000023
FILE_DEVICE_VIRTUAL_DISK        = 0x00000024
FILE_DEVICE_WAVE_IN             = 0x00000025
FILE_DEVICE_WAVE_OUT            = 0x00000026
FILE_DEVICE_8042_PORT           = 0x00000027
FILE_DEVICE_NETWORK_REDIRECTOR  = 0x00000028
FILE_DEVICE_BATTERY             = 0x00000029
FILE_DEVICE_BUS_EXTENDER        = 0x0000002a
FILE_DEVICE_MODEM               = 0x0000002b
FILE_DEVICE_VDM                 = 0x0000002c
FILE_DEVICE_MASS_STORAGE        = 0x0000002d
FILE_DEVICE_SMB                 = 0x0000002e
FILE_DEVICE_KS                  = 0x0000002f
FILE_DEVICE_CHANGER             = 0x00000030
FILE_DEVICE_SMARTCARD           = 0x00000031
FILE_DEVICE_ACPI                = 0x00000032
FILE_DEVICE_DVD                 = 0x00000033
FILE_DEVICE_FULLSCREEN_VIDEO    = 0x00000034
FILE_DEVICE_DFS_FILE_SYSTEM     = 0x00000035
FILE_DEVICE_DFS_VOLUME          = 0x00000036
FILE_DEVICE_SERENUM             = 0x00000037
FILE_DEVICE_TERMSRV             = 0x00000038
FILE_DEVICE_KSEC                = 0x00000039
FILE_DEVICE_FIPS                = 0x0000003A
FILE_DEVICE_INFINIBAND          = 0x0000003B
FILE_DEVICE_VMBUS               = 0x0000003E
FILE_DEVICE_CRYPT_PROVIDER      = 0x0000003F
FILE_DEVICE_WPD                 = 0x00000040
FILE_DEVICE_BLUETOOTH           = 0x00000041

METHOD_BUFFERED                 = 0
METHOD_IN_DIRECT                = 1
METHOD_OUT_DIRECT               = 2
METHOD_NEITHER                  = 3

METHOD_DIRECT_TO_HARDWARE       = METHOD_IN_DIRECT
METHOD_DIRECT_FROM_HARDWARE     = METHOD_OUT_DIRECT

FILE_ANY_ACCESS                 = 0
FILE_SPECIAL_ACCESS             = FILE_ANY_ACCESS
FILE_READ_ACCESS                = 0x0001
FILE_WRITE_ACCESS               = 0x0002
FILE_READ_DATA                  = 0x0001
FILE_LIST_DIRECTORY             = 0x0001
FILE_WRITE_DATA                 = 0x0002
FILE_ADD_FILE                   = 0x0002
FILE_APPEND_DATA                = 0x0004
FILE_ADD_SUBDIRECTORY           = 0x0004
FILE_CREATE_PIPE_INSTANCE       = 0x0004
FILE_READ_EA                    = 0x0008
FILE_WRITE_EA                   = 0x0010
FILE_EXECUTE                    = 0x0020
FILE_TRAVERSE                   = 0x0020
FILE_DELETE_CHILD               = 0x0040
FILE_READ_ATTRIBUTES            = 0x0080
FILE_WRITE_ATTRIBUTES           = 0x0100
FILE_ALL_ACCESS                 = (STANDARD_RIGHTS_REQUIRED | SYNCHRONIZE | 0x1FF)


FILE_GENERIC_READ               = (STANDARD_RIGHTS_READ     |\
                                   FILE_READ_DATA           |\
                                   FILE_READ_ATTRIBUTES     |\
                                   FILE_READ_EA             |\
                                   SYNCHRONIZE)

FILE_GENERIC_WRITE              = (STANDARD_RIGHTS_WRITE    |\
                                   FILE_WRITE_DATA          |\
                                   FILE_WRITE_ATTRIBUTES    |\
                                   FILE_WRITE_EA            |\
                                   FILE_APPEND_DATA         |\
                                   SYNCHRONIZE)

FILE_GENERIC_EXECUTE            = (STANDARD_RIGHTS_EXECUTE  |\
                                   FILE_READ_ATTRIBUTES     |\
                                   FILE_EXECUTE             |\
                                   SYNCHRONIZE)


FILE_SHARE_READ                     = 0x00000001
FILE_SHARE_WRITE                    = 0x00000002
FILE_SHARE_DELETE                   = 0x00000004
FILE_ATTRIBUTE_READONLY             = 0x00000001
FILE_ATTRIBUTE_HIDDEN               = 0x00000002
FILE_ATTRIBUTE_SYSTEM               = 0x00000004
FILE_ATTRIBUTE_DIRECTORY            = 0x00000010
FILE_ATTRIBUTE_ARCHIVE              = 0x00000020
FILE_ATTRIBUTE_DEVICE               = 0x00000040
FILE_ATTRIBUTE_NORMAL               = 0x00000080
FILE_ATTRIBUTE_TEMPORARY            = 0x00000100
FILE_ATTRIBUTE_SPARSE_FILE          = 0x00000200
FILE_ATTRIBUTE_REPARSE_POINT        = 0x00000400
FILE_ATTRIBUTE_COMPRESSED           = 0x00000800
FILE_ATTRIBUTE_OFFLINE              = 0x00001000
FILE_ATTRIBUTE_NOT_CONTENT_INDEXED  = 0x00002000
FILE_ATTRIBUTE_ENCRYPTED            = 0x00004000
FILE_ATTRIBUTE_VIRTUAL              = 0x00010000
FILE_NOTIFY_CHANGE_FILE_NAME        = 0x00000001
FILE_NOTIFY_CHANGE_DIR_NAME         = 0x00000002
FILE_NOTIFY_CHANGE_ATTRIBUTES       = 0x00000004
FILE_NOTIFY_CHANGE_SIZE             = 0x00000008
FILE_NOTIFY_CHANGE_LAST_WRITE       = 0x00000010
FILE_NOTIFY_CHANGE_LAST_ACCESS      = 0x00000020
FILE_NOTIFY_CHANGE_CREATION         = 0x00000040
FILE_NOTIFY_CHANGE_SECURITY         = 0x00000100
FILE_ACTION_ADDED                   = 0x00000001
FILE_ACTION_REMOVED                 = 0x00000002
FILE_ACTION_MODIFIED                = 0x00000003
FILE_ACTION_RENAMED_OLD_NAME        = 0x00000004
FILE_ACTION_RENAMED_NEW_NAME        = 0x00000005
MAILSLOT_NO_MESSAGE                 = -1
MAILSLOT_WAIT_FOREVER               = -1



FSCTL_REQUEST_OPLOCK_LEVEL_1    = CTL_CODE(FILE_DEVICE_FILE_SYSTEM,  0, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_REQUEST_OPLOCK_LEVEL_2    = CTL_CODE(FILE_DEVICE_FILE_SYSTEM,  1, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_REQUEST_BATCH_OPLOCK      = CTL_CODE(FILE_DEVICE_FILE_SYSTEM,  2, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_OPLOCK_BREAK_ACKNOWLEDGE  = CTL_CODE(FILE_DEVICE_FILE_SYSTEM,  3, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_OPBATCH_ACK_CLOSE_PENDING = CTL_CODE(FILE_DEVICE_FILE_SYSTEM,  4, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_OPLOCK_BREAK_NOTIFY       = CTL_CODE(FILE_DEVICE_FILE_SYSTEM,  5, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_LOCK_VOLUME               = CTL_CODE(FILE_DEVICE_FILE_SYSTEM,  6, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_UNLOCK_VOLUME             = CTL_CODE(FILE_DEVICE_FILE_SYSTEM,  7, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_DISMOUNT_VOLUME           = CTL_CODE(FILE_DEVICE_FILE_SYSTEM,  8, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_IS_VOLUME_MOUNTED         = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 10, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_IS_PATHNAME_VALID         = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 11, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_MARK_VOLUME_DIRTY         = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 12, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_QUERY_RETRIEVAL_POINTERS  = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 14,  METHOD_NEITHER, FILE_ANY_ACCESS)
FSCTL_GET_COMPRESSION           = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 15, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_SET_COMPRESSION           = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 16, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
FSCTL_MARK_AS_SYSTEM_HIVE       = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 19,  METHOD_NEITHER, FILE_ANY_ACCESS)
FSCTL_OPLOCK_BREAK_ACK_NO_2     = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 20, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_INVALIDATE_VOLUMES        = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 21, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_QUERY_FAT_BPB             = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 22, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_REQUEST_FILTER_OPLOCK     = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 23, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_FILESYSTEM_GET_STATISTICS = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 24, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_GET_NTFS_VOLUME_DATA      = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 25, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_GET_NTFS_FILE_RECORD      = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 26, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_GET_VOLUME_BITMAP         = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 27,  METHOD_NEITHER, FILE_ANY_ACCESS)
FSCTL_GET_RETRIEVAL_POINTERS    = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 28,  METHOD_NEITHER, FILE_ANY_ACCESS)
FSCTL_MOVE_FILE                 = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 29, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
FSCTL_IS_VOLUME_DIRTY           = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 30, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_ALLOW_EXTENDED_DASD_IO    = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 32, METHOD_NEITHER,  FILE_ANY_ACCESS)
FSCTL_FIND_FILES_BY_SID         = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 35, METHOD_NEITHER, FILE_ANY_ACCESS)
FSCTL_SET_OBJECT_ID             = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 38, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
FSCTL_GET_OBJECT_ID             = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 39, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_DELETE_OBJECT_ID          = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 40, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
FSCTL_SET_REPARSE_POINT         = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 41, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
FSCTL_GET_REPARSE_POINT         = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 42, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_DELETE_REPARSE_POINT      = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 43, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
FSCTL_ENUM_USN_DATA             = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 44,  METHOD_NEITHER, FILE_ANY_ACCESS)
FSCTL_SECURITY_ID_CHECK         = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 45,  METHOD_NEITHER, FILE_READ_DATA)
FSCTL_READ_USN_JOURNAL          = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 46,  METHOD_NEITHER, FILE_ANY_ACCESS)
FSCTL_SET_OBJECT_ID_EXTENDED    = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 47, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
FSCTL_CREATE_OR_GET_OBJECT_ID   = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 48, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_SET_SPARSE                = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 49, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
FSCTL_SET_ZERO_DATA             = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 50, METHOD_BUFFERED, FILE_WRITE_DATA)
FSCTL_QUERY_ALLOCATED_RANGES    = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 51,  METHOD_NEITHER, FILE_READ_DATA)
FSCTL_ENABLE_UPGRADE            = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 52, METHOD_BUFFERED, FILE_WRITE_DATA)
FSCTL_SET_ENCRYPTION            = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 53,  METHOD_NEITHER, FILE_ANY_ACCESS)
FSCTL_ENCRYPTION_FSCTL_IO       = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 54,  METHOD_NEITHER, FILE_ANY_ACCESS)
FSCTL_WRITE_RAW_ENCRYPTED       = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 55,  METHOD_NEITHER, FILE_SPECIAL_ACCESS)
FSCTL_READ_RAW_ENCRYPTED        = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 56,  METHOD_NEITHER, FILE_SPECIAL_ACCESS)
FSCTL_CREATE_USN_JOURNAL        = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 57,  METHOD_NEITHER, FILE_ANY_ACCESS)
FSCTL_READ_FILE_USN_DATA        = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 58,  METHOD_NEITHER, FILE_ANY_ACCESS)
FSCTL_WRITE_USN_CLOSE_RECORD    = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 59,  METHOD_NEITHER, FILE_ANY_ACCESS)
FSCTL_EXTEND_VOLUME             = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 60, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_QUERY_USN_JOURNAL         = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 61, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_DELETE_USN_JOURNAL        = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 62, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_MARK_HANDLE               = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 63, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_SIS_COPYFILE              = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 64, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_SIS_LINK_FILES            = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 65, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
FSCTL_HSM_MSG                   = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 66, METHOD_BUFFERED, FILE_READ_DATA | FILE_WRITE_DATA)
FSCTL_HSM_DATA                  = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 68, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
FSCTL_RECALL_FILE               = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 69, METHOD_NEITHER, FILE_ANY_ACCESS)
FSCTL_READ_FROM_PLEX            = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 71, METHOD_OUT_DIRECT, FILE_READ_DATA)
FSCTL_FILE_PREFETCH             = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 72, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
FSCTL_MAKE_MEDIA_COMPATIBLE         = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 76, METHOD_BUFFERED, FILE_WRITE_DATA)
FSCTL_SET_DEFECT_MANAGEMENT         = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 77, METHOD_BUFFERED, FILE_WRITE_DATA)
FSCTL_QUERY_SPARING_INFO            = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 78, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_QUERY_ON_DISK_VOLUME_INFO     = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 79, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_SET_VOLUME_COMPRESSION_STATE  = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 80, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
FSCTL_TXFS_MODIFY_RM                = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 81, METHOD_BUFFERED, FILE_WRITE_DATA)
FSCTL_TXFS_QUERY_RM_INFORMATION     = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 82, METHOD_BUFFERED, FILE_READ_DATA)
FSCTL_TXFS_ROLLFORWARD_REDO         = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 84, METHOD_BUFFERED, FILE_WRITE_DATA)
FSCTL_TXFS_ROLLFORWARD_UNDO         = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 85, METHOD_BUFFERED, FILE_WRITE_DATA)
FSCTL_TXFS_START_RM                 = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 86, METHOD_BUFFERED, FILE_WRITE_DATA)
FSCTL_TXFS_SHUTDOWN_RM              = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 87, METHOD_BUFFERED, FILE_WRITE_DATA)
FSCTL_TXFS_READ_BACKUP_INFORMATION  = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 88, METHOD_BUFFERED, FILE_READ_DATA)
FSCTL_TXFS_WRITE_BACKUP_INFORMATION = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 89, METHOD_BUFFERED, FILE_WRITE_DATA)
FSCTL_TXFS_CREATE_SECONDARY_RM      = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 90, METHOD_BUFFERED, FILE_WRITE_DATA)
FSCTL_TXFS_GET_METADATA_INFO        = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 91, METHOD_BUFFERED, FILE_READ_DATA)
FSCTL_TXFS_GET_TRANSACTED_VERSION   = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 92, METHOD_BUFFERED, FILE_READ_DATA)
FSCTL_TXFS_CREATE_MINIVERSION       = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 95, METHOD_BUFFERED, FILE_WRITE_DATA)
FSCTL_TXFS_TRANSACTION_ACTIVE       = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 99, METHOD_BUFFERED, FILE_READ_DATA)
FSCTL_SET_ZERO_ON_DEALLOCATION      = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 101, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
FSCTL_SET_REPAIR                    = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 102, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_GET_REPAIR                    = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 103, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_WAIT_FOR_REPAIR               = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 104, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_INITIATE_REPAIR               = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 106, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_CSC_INTERNAL                  = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 107, METHOD_NEITHER, FILE_ANY_ACCESS)
FSCTL_SHRINK_VOLUME                 = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 108, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
FSCTL_SET_SHORT_NAME_BEHAVIOR       = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 109, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_DFSR_SET_GHOST_HANDLE_STATE   = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 110, METHOD_BUFFERED, FILE_ANY_ACCESS)
FSCTL_TXFS_LIST_TRANSACTION_LOCKED_FILES \
                                            = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 120, METHOD_BUFFERED, FILE_READ_DATA)
FSCTL_TXFS_LIST_TRANSACTIONS        = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 121, METHOD_BUFFERED, FILE_READ_DATA)
FSCTL_QUERY_PAGEFILE_ENCRYPTION     = CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 122, METHOD_BUFFERED, FILE_ANY_ACCESS)
